version: "3.4"

services:

  web:
    build: "."
    container_name: pyramid
    labels:
      "autoheal": "true"
    expose:
     - "6543"
    network_mode: "host"

  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
      - AUTOHEAL_INTERVAL=10
  